hosts:
  - localhost:8091
username: user
password: password
bucketName: dcp-test
scopeName: _default
collectionNames:
  - _default
metadata:
  type: kafka
  config:
    topic: dcp-test-connect-offset.0
    replicationFactor: 1 # default 3
    # partition: 25
dcp:
  group:
    name: groupName
    membership:
      type: static
kafka:
  collectionTopicMapping:
    _default: topicname
  brokers:
    - localhost:9092
  # SSL configurations
  #
  # secureConnection: true
  # Config support env variable "$HOME/example/..."
  # rootCAPath: "example/stretch-kafka/rootCA.pem"
  # interCAPath: "example/stretch-kafka/interCA.pem"
  # scramUsername: "username"
  # scramPassword: "password"
checkpoint:
  type: manual